repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-json
  - id: pretty-format-json
    args:
    - --autofix
    - --indent
    - "4"
- repo: local
  hooks:
  - id: black
    name: black
    entry: pipenv run black apps/controllerx tests
    language: system
    pass_filenames: false
    always_run: true
  - id: flake8
    name: flake8
    entry: pipenv run flake8 apps/controllerx
    language: system
    pass_filenames: false
    always_run: true
  - id: mypy
    name: mypy
    entry: pipenv run mypy apps/controllerx
    language: system
    pass_filenames: false
    always_run: true
  - id: pytest
    name: pytest
    entry: pipenv run pytest
    language: system
    pass_filenames: false
    always_run: true