fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: pipenv run isort
        language: python
        types: [python]
        args: []
        require_serial: false
      - id: black
        name: black
        entry: pipenv run black
        language: python
        types: [python]
      - id: flake8
        name: flake8
        entry: pipenv run flake8
        language: python
        types: [python]
      - id: mypy
        name: mypy
        entry: pipenv run mypy --install-types --non-interactive
        language: python
        types: [python]
      - id: pytest
        name: pytest
        entry: pipenv run pytest
        language: python
        files: "(.*.py)|apps/controllerx/*|tests/*"
        pass_filenames: false
