site_name: ControllerX

repo_name: xaviml/controllerx
repo_url: https://github.com/xaviml/controllerx

nav:
  - index.md
  - Start:
      - Installation: start/installation.md
      - Configuration: start/configuration.md
      - Type Configuration: start/type-configuration.md
      - Integrations: others/integrations.md
  - Supported controllers: controllers.md
  - Examples:
      - Real Examples: examples/index.md
      - Advanced:
          - examples/sonos-display.md
          - examples/sonos.md
          - examples/tasmota-switchmode11.md
  - Advanced:
      - Custom mapping:
          - Basics: advanced/custom-controllers.md
          - advanced/action-types.md
          - advanced/predefined-actions.md
          - advanced/multiple-clicks.md
          - advanced/hold-click-modes.md
      - advanced/templating.md
      - advanced/entity-groups.md
  - Others:
      - others/extract-controller-id.md
      - others/run-appdaemon.md
      - others/update.md
  - faq.md

theme:
  name: material
  icon:
    repo: material/github
  logo: assets/logo_white.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - macros
  - gen-files:
      scripts:
        - gen_device_pages.py # or any other name or path

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false
      anchor_linenums: true
  - attr_list
